language: java
sudo: false
script: mvn clean verify
services:
  - mysql
notifications:
  slack: votingwithblockchain:VnDvMRUnVTwnjwTkq3HzGWEc
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE prototype;'
  - mysql -e 'create TABLE Election (
                  id INTEGER not null,
                  name VARCHAR(255) not null,
                  startDate DATE not null,
                  endDate DATE not null,
                  PRIMARY KEY (id)
              );'

